import { SafeAreaProvider } from 'react-native-safe-area-context'
import { StatusBar } from 'expo-status-bar'
import { WdkAppProvider } from '@tetherto/wdk-react-native-core'
import { useFonts } from 'expo-font'
import {
  IBMPlexSans_400Regular,
  IBMPlexSans_500Medium,
  IBMPlexSans_600SemiBold,
  IBMPlexSans_700Bold
} from '@expo-google-fonts/ibm-plex-sans'
import {
  IBMPlexMono_400Regular,
  IBMPlexMono_500Medium
} from '@expo-google-fonts/ibm-plex-mono'

import wdkConfigs from './src/wdk/config'
import { Root } from './src/Root'
import { ThemeProvider, useDark } from './src/useTheme'

// Generated by `wdk-worklet-bundler generate` (postinstall). Gitignored.
// Contains WDK *and* the Holepunch address book — one worklet, two stacks.
const workletBundle = require('./.wdk-bundle/wdk-worklet.bundle.js')

export default function App () {
  // The files ship with the app, so this is a local read rather than a download — fast, and
  // it works offline. Rendering is held until they land: every screen names a Plex family
  // explicitly, and painting one frame in the system font first is a visible flash.
  const [fontsLoaded] = useFonts({
    IBMPlexSans_400Regular,
    IBMPlexSans_500Medium,
    IBMPlexSans_600SemiBold,
    IBMPlexSans_700Bold,
    IBMPlexMono_400Regular,
    IBMPlexMono_500Medium
  })

  if (!fontsLoaded) return null

  return (
    <ThemeProvider>
      <SafeAreaProvider>
        <Chrome />
        <WdkAppProvider bundle={{ bundle: workletBundle }} wdkConfigs={wdkConfigs}>
          <Root />
        </WdkAppProvider>
      </SafeAreaProvider>
    </ThemeProvider>
  )
}

/**
 * The status bar has to follow the app's theme, not the phone's.
 * `style="auto"` reads the OS setting, which is wrong the moment somebody overrides it in
 * Menu — dark text on a dark screen.
 */
function Chrome () {
  return <StatusBar style={useDark() ? 'light' : 'dark'} />
}
